# Generated by Django 3.2.4 on 2021-06-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_food.company'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('TURKISH', 'TURKISH'), ('KYRGYZ', 'KYRGYZ'), ('JAPANESE', 'JAPANESE'), ('FAST_FOOD', 'FAST_FOOD'), ('KOREAN', 'KOREAN'), ('EUROPEAN', 'EUROPEAN'), ('VEGETARIAN', 'VEGETARIAN'), ('OTHER', 'OTHER')], max_length=100, null=True),
        ),
    ]
