# Generated by Django 3.2.4 on 2021-06-08 14:12

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('CLIENT', 'CLIENT')], max_length=100)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('number', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_stuff', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
